version: 2.1
## Add reusable components
commands:
  makeApp:
    description: "Lint, test, build and harvest android app"
    parameters:
      variantname:
        type: string
        default: "HungarianGooglePlayRelease"

    docker:
      - image: circleci/android:api-29-ndk

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - run: echo << parameters.variantname >>
      - run:
          name: Lint source
          command: ./gradlew lint<< parameters.variantname >>
      - run:
          name: Run tests
          command: ./gradlew test<< parameters.variantname >>UnitTest
      - run:
          name: Compile
          command: ./gradlew compile<< parameters.variantname >>Sources

      - run:
          name: Assemble Unsigned APK
          command: ./gradlew assembleH<< parameters.variantname >>

      - store_test_results:
          path: mobile/build/test-results
      
      - store_artifacts:
          path: mobile/build/reports
          destination: build-reports
     
      - store_artifacts:
          path: mobile/build/outputs
          destination: outputs

### Define actual jobs
jobs:
  build:
    docker:
      - image: circleci/android:api-29-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "mobile/build.gradle" }}
      - run: ./.circleci/pre-build.sh
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "mobile/build.gradle" }}

      ## Build apps individually
      - makeApp:
          variantName: "HungarianGooglePlayRelease"

      # - run:
      #     name: Lint source and Tests
      #     command: ./gradlew lintHungarianRelease testHungarianReleaseUnitTest

      # - run:
      #     name: Compile
      #     command: ./gradlew compileHungarianReleaseSources

      # - run:
      #     name: Assemble Unsigned APK
      #     command: ./gradlew assembleHungarianRelease

      # - store_test_results:
      #     path: mobile/build/test-results
      
      # - store_artifacts:
      #     path: mobile/build/reports
      #     destination: build-reports
     
      # - store_artifacts:
      #     path: mobile/build/outputs
      #     destination: outputs

      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples